trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'Azureserviceconnection'
    KeyVaultName: 'poc38-keyvault'
    SecretsFilter: 'ApiKey'
    RunAsPreJob: true

- script: |
    echo "Before substitution"
    cat appsettings.json

    sed -i "s|__API_KEY__|$(ApiKey)|g" appsettings.json

    echo "After substitution"
    cat appsettings.json
  displayName: 'Inject Key Vault Secret'